require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FavoritosController do

  # This should return the minimal set of attributes required to create a valid
  # Favorito. As you add validations to Favorito, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nomeLocal" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FavoritosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all favoritos as @favoritos" do
      favorito = Favorito.create! valid_attributes
      get :index, {}, valid_session
      assigns(:favoritos).should eq([favorito])
    end
  end

  describe "GET show" do
    it "assigns the requested favorito as @favorito" do
      favorito = Favorito.create! valid_attributes
      get :show, {:id => favorito.to_param}, valid_session
      assigns(:favorito).should eq(favorito)
    end
  end

  describe "GET new" do
    it "assigns a new favorito as @favorito" do
      get :new, {}, valid_session
      assigns(:favorito).should be_a_new(Favorito)
    end
  end

  describe "GET edit" do
    it "assigns the requested favorito as @favorito" do
      favorito = Favorito.create! valid_attributes
      get :edit, {:id => favorito.to_param}, valid_session
      assigns(:favorito).should eq(favorito)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Favorito" do
        expect {
          post :create, {:favorito => valid_attributes}, valid_session
        }.to change(Favorito, :count).by(1)
      end

      it "assigns a newly created favorito as @favorito" do
        post :create, {:favorito => valid_attributes}, valid_session
        assigns(:favorito).should be_a(Favorito)
        assigns(:favorito).should be_persisted
      end

      it "redirects to the created favorito" do
        post :create, {:favorito => valid_attributes}, valid_session
        response.should redirect_to(Favorito.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved favorito as @favorito" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favorito.any_instance.stub(:save).and_return(false)
        post :create, {:favorito => { "nomeLocal" => "invalid value" }}, valid_session
        assigns(:favorito).should be_a_new(Favorito)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Favorito.any_instance.stub(:save).and_return(false)
        post :create, {:favorito => { "nomeLocal" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested favorito" do
        favorito = Favorito.create! valid_attributes
        # Assuming there are no other favoritos in the database, this
        # specifies that the Favorito created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Favorito.any_instance.should_receive(:update).with({ "nomeLocal" => "MyString" })
        put :update, {:id => favorito.to_param, :favorito => { "nomeLocal" => "MyString" }}, valid_session
      end

      it "assigns the requested favorito as @favorito" do
        favorito = Favorito.create! valid_attributes
        put :update, {:id => favorito.to_param, :favorito => valid_attributes}, valid_session
        assigns(:favorito).should eq(favorito)
      end

      it "redirects to the favorito" do
        favorito = Favorito.create! valid_attributes
        put :update, {:id => favorito.to_param, :favorito => valid_attributes}, valid_session
        response.should redirect_to(favorito)
      end
    end

    describe "with invalid params" do
      it "assigns the favorito as @favorito" do
        favorito = Favorito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favorito.any_instance.stub(:save).and_return(false)
        put :update, {:id => favorito.to_param, :favorito => { "nomeLocal" => "invalid value" }}, valid_session
        assigns(:favorito).should eq(favorito)
      end

      it "re-renders the 'edit' template" do
        favorito = Favorito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Favorito.any_instance.stub(:save).and_return(false)
        put :update, {:id => favorito.to_param, :favorito => { "nomeLocal" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested favorito" do
      favorito = Favorito.create! valid_attributes
      expect {
        delete :destroy, {:id => favorito.to_param}, valid_session
      }.to change(Favorito, :count).by(-1)
    end

    it "redirects to the favoritos list" do
      favorito = Favorito.create! valid_attributes
      delete :destroy, {:id => favorito.to_param}, valid_session
      response.should redirect_to(favoritos_url)
    end
  end

end
