require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PosicionamentosController do

  # This should return the minimal set of attributes required to create a valid
  # Posicionamento. As you add validations to Posicionamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "posicao" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PosicionamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all posicionamentos as @posicionamentos" do
      posicionamento = Posicionamento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:posicionamentos).should eq([posicionamento])
    end
  end

  describe "GET show" do
    it "assigns the requested posicionamento as @posicionamento" do
      posicionamento = Posicionamento.create! valid_attributes
      get :show, {:id => posicionamento.to_param}, valid_session
      assigns(:posicionamento).should eq(posicionamento)
    end
  end

  describe "GET new" do
    it "assigns a new posicionamento as @posicionamento" do
      get :new, {}, valid_session
      assigns(:posicionamento).should be_a_new(Posicionamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested posicionamento as @posicionamento" do
      posicionamento = Posicionamento.create! valid_attributes
      get :edit, {:id => posicionamento.to_param}, valid_session
      assigns(:posicionamento).should eq(posicionamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Posicionamento" do
        expect {
          post :create, {:posicionamento => valid_attributes}, valid_session
        }.to change(Posicionamento, :count).by(1)
      end

      it "assigns a newly created posicionamento as @posicionamento" do
        post :create, {:posicionamento => valid_attributes}, valid_session
        assigns(:posicionamento).should be_a(Posicionamento)
        assigns(:posicionamento).should be_persisted
      end

      it "redirects to the created posicionamento" do
        post :create, {:posicionamento => valid_attributes}, valid_session
        response.should redirect_to(Posicionamento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved posicionamento as @posicionamento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Posicionamento.any_instance.stub(:save).and_return(false)
        post :create, {:posicionamento => { "posicao" => "invalid value" }}, valid_session
        assigns(:posicionamento).should be_a_new(Posicionamento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Posicionamento.any_instance.stub(:save).and_return(false)
        post :create, {:posicionamento => { "posicao" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested posicionamento" do
        posicionamento = Posicionamento.create! valid_attributes
        # Assuming there are no other posicionamentos in the database, this
        # specifies that the Posicionamento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Posicionamento.any_instance.should_receive(:update).with({ "posicao" => "MyString" })
        put :update, {:id => posicionamento.to_param, :posicionamento => { "posicao" => "MyString" }}, valid_session
      end

      it "assigns the requested posicionamento as @posicionamento" do
        posicionamento = Posicionamento.create! valid_attributes
        put :update, {:id => posicionamento.to_param, :posicionamento => valid_attributes}, valid_session
        assigns(:posicionamento).should eq(posicionamento)
      end

      it "redirects to the posicionamento" do
        posicionamento = Posicionamento.create! valid_attributes
        put :update, {:id => posicionamento.to_param, :posicionamento => valid_attributes}, valid_session
        response.should redirect_to(posicionamento)
      end
    end

    describe "with invalid params" do
      it "assigns the posicionamento as @posicionamento" do
        posicionamento = Posicionamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Posicionamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => posicionamento.to_param, :posicionamento => { "posicao" => "invalid value" }}, valid_session
        assigns(:posicionamento).should eq(posicionamento)
      end

      it "re-renders the 'edit' template" do
        posicionamento = Posicionamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Posicionamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => posicionamento.to_param, :posicionamento => { "posicao" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested posicionamento" do
      posicionamento = Posicionamento.create! valid_attributes
      expect {
        delete :destroy, {:id => posicionamento.to_param}, valid_session
      }.to change(Posicionamento, :count).by(-1)
    end

    it "redirects to the posicionamentos list" do
      posicionamento = Posicionamento.create! valid_attributes
      delete :destroy, {:id => posicionamento.to_param}, valid_session
      response.should redirect_to(posicionamentos_url)
    end
  end

end
